#!/usr/bin/env python3
"""Build a batates skin from a folder of per-frame PNGs.

Emits a strict rows x columns sprite sheet plus the skin.ron manifest that
describes it. Row order is the PetState order in src/core/brain.rs; the Rust
side derives every frame index as row * columns + n, so the manifest and the
sheet must agree or nothing lines up.

Usage:
    make_sprite.py <input-dir> --out <skin-dir> [--frame-size 50] [--fps 12]

Input filenames must be <state>_<frame>.png, e.g. walk_03.png.
"""

import argparse
import os
import re
import sys

from PIL import Image

# Position in this list IS the sheet row. Keep in sync with PetState::ALL.
STATES = [
    ("chill", "Chilling"),
    ("drag", "Dragged"),
    ("eat", "Eating"),
    ("idle", "Idle"),
    ("jump", "Jumping"),
    ("love", "SendingLove"),
    ("sit", "Sitting"),
    ("walk", "Walking"),
]

# Default behaviour per state. Hand-edit the generated manifest to taste; every
# transition list must be non-empty or the Rust loader rejects the skin.
#
# For "Once" states the duration is only a backstop: the Rust side extends it to
# at least the animation's own length, so a reaction always plays to the end.
BEHAVIOUR = {
    "Chilling": ("Loop", (4.0, 12.0), "Still", [("Idle", 3), ("Walking", 2), ("Sitting", 1)]),
    "Dragged": ("Loop", (0.0, 0.0), "Held", [("Sitting", 1)]),
    "Eating": ("Once", (3.0, 6.0), "Still", [("Idle", 2), ("Chilling", 1)]),
    "Idle": ("Loop", (3.0, 10.0), "Still",
             [("Walking", 3), ("Chilling", 2), ("Sitting", 1), ("Eating", 1)]),
    "Jumping": ("Once", (0.9, 0.9), "Still", [("Idle", 1)]),
    "SendingLove": ("Once", (2.0, 2.0), "Still", [("Idle", 1)]),
    "Sitting": ("Loop", (5.0, 20.0), "Still", [("Idle", 2), ("Eating", 1), ("Chilling", 1)]),
    "Walking": ("Loop", (2.0, 8.0), "Walk(speed: 140.0)", [("Idle", 3), ("Sitting", 1)]),
}

FRAME_PATTERN = re.compile(r"([a-zA-Z]+)_(\d+)\.png$")


def load_frames(folder):
    """Returns {prefix: [Image, ...]} ordered by frame number."""
    found = {prefix: [] for prefix, _ in STATES}
    known = set(found)

    for filename in sorted(os.listdir(folder)):
        match = FRAME_PATTERN.match(filename)
        if not match:
            continue
        prefix, number = match.group(1), int(match.group(2))
        if prefix not in known:
            print(f"warning: ignoring unknown state '{prefix}' in {filename}", file=sys.stderr)
            continue
        found[prefix].append((number, os.path.join(folder, filename)))

    missing = [prefix for prefix, frames in found.items() if not frames]
    if missing:
        raise SystemExit(
            f"error: no frames for state(s): {', '.join(missing)}.\n"
            "A skin must implement all eight states."
        )

    return {
        prefix: [Image.open(path) for _, path in sorted(frames)]
        for prefix, frames in found.items()
    }


def build_sheet(frames, frame_size, out_path):
    """Writes the sheet and returns its column count."""
    columns = max(len(images) for images in frames.values())
    sheet = Image.new("RGBA", (frame_size * columns, frame_size * len(STATES)))

    for row, (prefix, _) in enumerate(STATES):
        for column, image in enumerate(frames[prefix]):
            sheet.paste(image.resize((frame_size, frame_size)), (column * frame_size, row * frame_size))

    sheet.save(out_path)
    return columns


def build_manifest(name, frames, columns, frame_size, fps):
    lines = [
        "// Generated by scripts/make_sprite.py. Row order is the state order below;",
        "// the sheet is a strict rows x columns grid.",
        "SkinManifest(",
        f'    name: "{name}",',
        '    sheet: "sheet.png",',
        f"    frame_size: ({frame_size}, {frame_size}),",
        f"    columns: {columns},",
        f"    default_fps: {fps},",
        "    states: [",
    ]

    for prefix, state in STATES:
        count = len(frames[prefix])
        playback, (lo, hi), locomotion, transitions = BEHAVIOUR[state]
        # A single-frame state has nothing to animate; slow its clock so it
        # does not spin the frame timer needlessly.
        fps_line = f"\n            fps: Some(1)," if count == 1 else ""
        joined = ", ".join(f"(to: {to}, weight: {weight})" for to, weight in transitions)
        lines += [
            "        (",
            f"            state: {state},",
            f"            frames: {count},{fps_line}",
            f"            playback: {playback},",
            f"            duration: ({lo}, {hi}),",
            f"            locomotion: {locomotion},",
            f"            transitions: [{joined}],",
            "        ),",
        ]

    lines += ["    ],", ")", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", help="folder of <state>_<frame>.png files")
    parser.add_argument("--out", required=True, help="skin directory to write")
    parser.add_argument("--frame-size", type=int, default=50)
    parser.add_argument("--fps", type=int, default=12)
    args = parser.parse_args()

    if not os.path.isdir(args.input):
        raise SystemExit(f"error: {args.input} is not a directory")

    frames = load_frames(args.input)
    os.makedirs(args.out, exist_ok=True)

    columns = build_sheet(frames, args.frame_size, os.path.join(args.out, "sheet.png"))
    name = os.path.basename(os.path.normpath(args.out))
    manifest = build_manifest(name, frames, columns, args.frame_size, args.fps)

    with open(os.path.join(args.out, "skin.ron"), "w") as handle:
        handle.write(manifest)

    print(f"wrote {args.out}/sheet.png ({columns} columns x {len(STATES)} rows)")
    print(f"wrote {args.out}/skin.ron")
    for prefix, state in STATES:
        print(f"  {state}: {len(frames[prefix])} frames")


if __name__ == "__main__":
    main()
